### PR TITLE
Updated manifests.yml to use buildpacks

### PR DESCRIPTION
**Pull request by ZKjellberg**
* buildpack is deprecated. Updated all manifest files to new 'buildpacks'
* Formatted python file to match PEP 8 Style Guide
* Added .DS_Store to .gitignore

See [Pull Request 1355 on cg-site](https://github.com/18F/cg-site/pull/1355) for related buildpack deprecation documentation updates.

### CODE REVIEW

**Comment by mxplusb** [comment]
@ZKjellberg if you can rebase and repush, assign to me and I'll look at it for you.

**Comment by ZKjellberg** [comment]
@mxplusb Looks like @bengerman13 completed the `buildpack` to `buildpacks` migration back in March.

I've now merged in master, which retains the changes for:
* Formatted python file to match PEP 8 Style Guide
* Added .DS_Store to .gitignore

**Comment by ZKjellberg** [comment]
@mxplusb I do not have permission to assign you this ticket.

**Comment by bengerman13** [comment]
thanks, @ZKjellberg!

**Pull request merged**
